2022-08-15 18:45:34,820 DEBUG    root            Loaded Command Group: ['gcloud', 'kms']
2022-08-15 18:45:34,823 DEBUG    root            Loaded Command Group: ['gcloud', 'kms', 'asymmetric_decrypt']
2022-08-15 18:45:34,824 DEBUG    root            Running [gcloud.kms.asymmetric-decrypt] with arguments: [--ciphertext-file: "-", --key: "cschlegel-28vcslbq-key", --keyring: "vpn-users-keyring", --location: "global", --plaintext-file: "-", --project: "ccs-platform-0d75", --version: "1"]
2022-08-15 18:45:35,378 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudkms.googleapis.com:443
2022-08-15 18:45:35,541 DEBUG    urllib3.connectionpool https://cloudkms.googleapis.com:443 "POST /v1/projects/ccs-platform-0d75/locations/global/keyRings/vpn-users-keyring/cryptoKeys/cschlegel-28vcslbq-key/cryptoKeyVersions/1:asymmetricDecrypt?alt=json HTTP/1.1" 400 None
2022-08-15 18:45:35,543 DEBUG    root            (gcloud.kms.asymmetric-decrypt) INVALID_ARGUMENT: Request field ciphertext is required.
Traceback (most recent call last):
  File "/Users/cori/google-cloud-sdk/lib/surface/kms/asymmetric_decrypt.py", line 112, in Run
    .AsymmetricDecrypt(req))
  File "/Users/cori/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/cloudkms/v1/cloudkms_v1_client.py", line 269, in AsymmetricDecrypt
    return self._RunMethod(
  File "/Users/cori/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/Users/cori/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/Users/cori/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpBadRequestError: HttpError accessing <https://cloudkms.googleapis.com/v1/projects/ccs-platform-0d75/locations/global/keyRings/vpn-users-keyring/cryptoKeys/cschlegel-28vcslbq-key/cryptoKeyVersions/1:asymmetricDecrypt?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Mon, 15 Aug 2022 23:45:35 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'transfer-encoding': 'chunked', 'status': 400}>, content <{
  "error": {
    "code": 400,
    "message": "Request field ciphertext is required.",
    "status": "INVALID_ARGUMENT"
  }
}
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cori/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/cori/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/Users/cori/google-cloud-sdk/lib/surface/kms/asymmetric_decrypt.py", line 116, in Run
    e2e_integrity.ProcessHttpBadRequestError(error)
  File "/Users/cori/google-cloud-sdk/lib/googlecloudsdk/command_lib/kms/e2e_integrity.py", line 90, in ProcessHttpBadRequestError
    raise exc
googlecloudsdk.calliope.exceptions.HttpException: INVALID_ARGUMENT: Request field ciphertext is required.
2022-08-15 18:45:35,546 ERROR    root            (gcloud.kms.asymmetric-decrypt) INVALID_ARGUMENT: Request field ciphertext is required.
